spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL_2}
    username: ${SPRING_DATASOURCE_USERNAME_2}
    password: ${SPRING_DATASOURCE_PASSWORD_2}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    baseline-on-migrate: true
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}

    consumer:
      group-id: tracking-service
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer

    listener:
      ack-mode: record

    properties:
      schema.registry.url: ${SPRING_SCHEMA_REGISTRY_URL}

      basic.auth.credentials.source: USER_INFO
      schema.registry.basic.auth.user.info: ${SPRING_SCHEMA_REGISTRY_API_KEY}:${SPRING_SCHEMA_REGISTRY_SECRET}

      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${SPRING_KAFKA_API_KEY}" password="${SPRING_KAFKA_API_SECRET}";
      specific.protobuf.value.type:
        com.danijelsudimac.shipmentservice.model.event.ShipmentCreatedEvent
application:
  notification-service:
    url: https://notification-service:8080