receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318


exporters:
  prometheusremotewrite:
    endpoint: ${env:PROMETHEUS_URL}
    auth:
      authenticator: sigv4auth

extensions:
  sigv4auth:
    region: us-east-2
    service: aps

service:
  extensions: [sigv4auth]

  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [prometheusremotewrite]